name: "book"

on:
  push:
    branches:
      - main


jobs:
  sphinx:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: cvxgrp/.github/actions/sphinx@main

  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: cvxgrp/.github/actions/coverage@main

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: cvxgrp/.github/actions/jupyter@main

  book:
    runs-on: "ubuntu-latest"
    needs: [test, sphinx, jupyter]

    permissions:
      contents: write

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download Book
        uses: actions/download-artifact@v4
        with:
          path: .book

      - name: GitHub Pages action
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages          # The branch the action should deploy to.
          folder: .book              # The folder the action should deploy.
