name: "book"

on:
- push

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/coverage@v2.0.12
        with:
          source-folder: src/mosek_tools
          tests-folder: src/tests

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/jupyter@v2.0.12

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/pdoc@v2.0.12
        with:
          source-folder: src/mosek_tools

  book:
    runs-on: "ubuntu-latest"
    needs: [test, jupyter, pdoc]

    permissions:
      contents: write

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/book@v2.0.12
