name: "book"

# Trigger the workflow on push events
# This ensures the documentation is automatically updated whenever code changes are pushed to main
on:
  push:
    branches:
      - main

jobs:
  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.72

      - uses: tschm/cradle/actions/pdoc@v0.1.72
        with:
          source-folder: 'src/mosek_tools'

  test:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read          # Minimal permissions for read-only operations
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.72

      - uses: tschm/cradle/actions/coverage@v0.1.72
        with:
          source-folder: 'src/mosek_tools'
          tests-folder: 'src/tests'

  jupyter:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read          # Minimal permissions for read-only operations
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.72

      - uses: tschm/cradle/actions/jupyter@v0.1.72

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter]

    permissions:
      pages: write            # Permission to deploy to Pages
      id-token: write         # Permission to verify deployment origin

    steps:
      #- name: Checkout [${{ github.repository }}]
      #  uses: actions/checkout@v4

      - uses: tschm/cradle/actions/book@v0.1.72
