name: "book"

on:
- push

jobs:
  #marimo:
  #  runs-on: "ubuntu-latest"
  #  steps:
  #    - uses: cvxgrp/.github/actions/uv/marimo@main

  #sphinx:
  #  runs-on: "ubuntu-latest"
  #  steps:
  #    - uses: cvxgrp/.github/actions/uv/sphinx@main

  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/uv/coverage@main
        with:
          source-folder: mosek_tools
  
  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/uv/jupyter@main

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/uv/pdoc@main
        with:
          source-folder: mosek_tools
          
  book:
    runs-on: "ubuntu-latest"
    needs: [test, jupyter, pdoc]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@main
