name: "book"

on:
- push

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/uv/coverage@v2.0.16
        with:
          source-folder: src/mosek_tools
          tests-folder: src/tests
          covaralls: 'false'

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/uv/jupyter@v2.0.16

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/uv/pdoc@v2.0.16
        with:
          source-folder: src/mosek_tools

  book:
    runs-on: "ubuntu-latest"
    needs: [test, jupyter, pdoc]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v2.0.16
