name: "book"

on:
- push

jobs:
  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: tschm/cradle/actions/pdoc@v0.1.57
        with:
          source-folder: 'src/mosek_tools'

  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: tschm/cradle/actions/coverage@v0.1.57
        with:
          source-folder: 'src/mosek_tools'
          tests-folder: 'src/tests'

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: tschm/cradle/actions/jupyter@v0.1.57

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter]

    permissions:
      contents: write

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: tschm/cradle/actions/book@v0.1.57
