name: "book"

on:
- push

jobs:
  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.4

      - uses: cvxgrp/.github/actions/pdoc@v2.2.4
        with:
          source-folder: 'src/mosek_tools'

  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.4

      - uses: cvxgrp/.github/actions/coverage@v2.2.4
        with:
          source-folder: 'src/mosek_tools'
          tests-folder: 'src/tests'

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/environment@v2.2.4

      - uses: cvxgrp/.github/actions/jupyter@v2.2.4

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v2.2.4
