name: "book"

on:
- push

jobs:
  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/uv/environment@v2.1.1

      - name: "Build the file"
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/mosek
          printf "%s" "${{ secrets.MOSEK_BASE64 }}" | base64 -d > ${{ github.workspace }}/mosek/mosek.lic
          # ls -all mosek
          # cat mosek/mosek.lic
          pwd
          #echo "End of story"

      - uses: cvxgrp/.github/actions/marimo@v2.1.1
        env:
          MOSEKLM_LICENSE_FILE: ${{ github.workspace }}/mosek/mosek.lic

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/uv/environment@v2.1.1

      - uses: cvxgrp/.github/actions/pdoc@v2.1.1
        with:
          source-folder: 'src/mosek_tools'

  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/uv/environment@v2.1.1

      - uses: cvxgrp/.github/actions/coverage@v2.1.1
        with:
          source-folder: 'src/mosek_tools'
          tests-folder: 'src/tests'

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: cvxgrp/.github/actions/uv/environment@v2.1.1

      - uses: cvxgrp/.github/actions/jupyter@v2.1.1

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter, marimo]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v2.1.1
