# This workflow builds and deploys marimo notebooks to GitHub Pages
# It runs automatically when changes are pushed to the main branch or can be triggered manually

name: MAINTENANCE

# Defines when the workflow will run
on:
  push

permissions:
  contents: 'read'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # Run pre-commit checks using the cradle action
      - uses: tschm/cradle/actions/pre-commit@v0.1.75

  test-notebooks:
    uses: jebel-quant/marimushka/.github/workflows/test.yml@v0.1.2
    with:
      notebook-dir: book/marimo

  deptry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: astral-sh/setup-uv@v6  # Official action for setting up uv

      - uses: tschm/cradle/actions/deptry@v0.1.75
        with:
          source-folder: 'src/mosek_tools'
