name: pre-commit

on:
  push:

jobs:    
  deptry:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/uv/deptry@v2.0.16
        with:
          source-folder: 'pyhrp'

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/uv/pre-commit@v2.0.16
