name: pre-commit

on:
  push:

jobs:
  deptry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/deptry@2.0.0
        with:
          source-folder: 'mosek_tools'
