name: pre-commit

permissions:
  contents: read

on:
  push:

jobs:
  deptry:
    runs-on: ubuntu-latest

    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.57

      - uses: cvxgrp/.github/actions/deptry@v2.2.8
        with:
          source-folder: 'src/mosek_tools'

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/pre-commit@v2.2.8
