name: Bump version and publish

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tagging:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_step.outputs.new_tag }}

    steps:
      - name: Generate Tag
        id: tag_step
        uses: tschm/cradle/actions/tag@v0.1.68
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: tagging
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: tschm/cradle/actions/build@v0.1.68
        with:
          tag: ${{ needs.tagging.outputs.new_tag }}
