name: Bump version and publish

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write  # Required for trusted publishing

jobs:
  tagging:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_step.outputs.new_tag }}

    steps:
      - name: Generate Tag
        id: tag_step
        uses: tschm/cradle/actions/tag@v0.1.66
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: tagging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for version tagging

      - name: Build
        uses: tschm/cradle/actions/build@v0.1.66
        with:
          tag: ${{ needs.tagging.outputs.new_tag }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      packages: write  # Add if publishing to GitHub Packages
      id-token: write  # Required for trusted publishing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish
        uses: tschm/cradle/actions/publish@main

      #- name: Checkout [${{ github.repository }}]
      #  uses: actions/checkout@v4

      #- uses: actions/download-artifact@v4
      #  with:
      #    name: dist
      #    path: dist

      #- name: Publish to PyPI
      #  uses: pypa/gh-action-pypi-publish@release/v1
